Updated roadmap
alphagov/pay-product-page pull request #692
Opened 2023-11-17 15:47 UTC by edoardo123-PAY

2023-11-17 15:58 UTC, nlsteers approved these changes

2023-11-17 16:07 UTC, Beth-Brown requested changes
There's one line that looks like it's been repeated (line 74 and 78)

2023-11-17 16:07 UTC, Beth-Brown commented on source/roadmap.html.erb
> +          We're planning to get the best new card payment suppliers, to make sure service teams and paying users have the best value for money and experience when using GOV.UK Pay.
This line duplicates line 74

2023-11-24 10:56 UTC, edoardo123-PAY commented on source/roadmap.html.erb
> +          We're planning to get the best new card payment suppliers, to make sure service teams and paying users have the best value for money and experience when using GOV.UK Pay.
Thanks Beth ! Great spot!

2023-11-24 11:01 UTC, edoardo123-PAY commented on source/roadmap.html.erb
> +         We're planning to get the best new card payment suppliers, to make sure service teams and paying users have the best value for money and experience when using GOV.UK Pay.
Need to change this

2023-11-24 11:01 UTC, edoardo123-PAY commented on source/roadmap.html.erb
> +         We're planning to get the best new card payment suppliers, to make sure service teams and paying users have the best value for money and experience when using GOV.UK Pay.
to this "We want to define a data organisation model to make Pay more efficient, improving performance and providing better value for money."

2023-11-24 12:54 UTC, edoardo123-PAY commented
Had to create a new branch with the changes, as there was an issue with the current branch.  Please look at this one instead - https://github.com/alphagov/pay-product-page/pull/694

2023-11-24 12:55 UTC, closed without merging